spring:
    cloud:
      gateway:
        routes:

          - id: enseignant-service
            uri: http://localhost:8080
            predicates:
              - Path=/api/enseignants/**
          - id: chercheur-service
            uri: http://localhost:8081
            predicates:
              - Path=/api/chercheurs/**
          - id: projet-service
            uri: http://localhost:8083
            predicates:
              - Path=/api/projets/**